apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: connectors.mgazza.github.com
spec:
  group: mgazza.github.com
  names:
    kind: Connector
    plural: connectors
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            config:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                "connector.class":
                  type: string
            status:
              type: object
      served: true
      storage: true
      subresources:
        status: {}
